### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gofish216** [mikumifa/cppTickerBuy#16]
### 部署方式

手动部署

### 版本

0.02

### 异常情况

点击抢票之后会出现这个未知错误的情况 不知道是哪出了问题 希望大佬救救QAQ

### 报错信息

![94A7F83DB2C6B636F3143A2A7A9D935A](https://github.com/user-attachments/assets/f6a9238b-6637-4863-9372-56b80cb48b4d)

**Comment by mikumifa** [comment]
风控问题，程序救不了
