### ISSUE TITLE
建议添加同一个身份和多个身份的多日购票功能

### ISSUE THREAD

**Issue by Dev-Apricity** [mikumifa/cppTickerBuy#2]
### 这是一个？

新功能

### 详细描述

现在的版本一次只能买一天，如果想买两天的就没办法了，跪求大佬优化 ( ･´ω`･ )

**Comment by mikumifa** [comment]
可以考虑

**Comment by MossCG** [comment]
为什么不多开呢.jpg

**Comment by mikumifa** [comment]
cpp可能要加验证码了，所以同时购票功能加不了

**Comment by Allroha** [comment]
> cpp可能要加验证码了，所以同时购票功能加不了

怎么说？有消息了吗

**Comment by MossCG** [comment]
> > cpp可能要加验证码了，所以同时购票功能加不了
> 
> 怎么说？有消息了吗

解决了

**Comment by mikumifa** [comment]
> 解决了

也不是完全解决了，只是验证码破了，但是验证码怎么除非这一块还没有例子，所有不确定

**Comment by Allroha** [comment]
> > 解决了
> 
> 也不是完全解决了，只是验证码破了，但是验证码怎么除非这一块还没有例子，所有不确定

![image](https://github.com/user-attachments/assets/9f14ac41-7274-4e45-8298-55234d5d09ec)
不知道要怎么解决呢
