### ISSUE TITLE
[Feature]: cp30在购票时似乎强制需要备注当天是否出cos

### ISSUE THREAD

**Issue by Alextraa** [mikumifa/cppTickerBuy#23]
### 这是一个？

现有功能优化

### 详细描述

根据最新政策要求,cp30无论是摊主入场和游客入场都需要备注是否出cos以及穿着什么角色的cos服装，而根据有人在cpp应用测试购票过程中的发现，游客买票时就需要在订单中备注是否出cos，请问会更新相关功能吗。

**Comment by mikumifa** [comment]
https://github.com/mikumifa/cppTickerBuy/discussions/19
