### ISSUE TITLE
[Bug]: 发行版报错：ValueError

### ISSUE THREAD

**Issue by tednved** [mikumifa/cppTickerBuy#40]
### 部署方式

release的打包文件

### 版本

v0.0.4

### 异常情况

直接运行exe文件会在弹出网址后不久弹出报错并退出进程

### 报错信息

<img width="707" alt="71980196eefde6102ae74906cfc6541f" src="https://github.com/user-attachments/assets/93569b4e-839d-436f-b497-f08abd3c4e1b">

**Comment by skpei** [comment]
相同报错，我把代理关了就没事了
