### ISSUE TITLE
[Feature]: 时间偏差更新方法的优化

### ISSUE THREAD

**Issue by DoubleFunny** [mikumifa/cppTickerBuy#43]
### 这是一个？

现有功能优化

### 详细描述

现在的自动更新时间偏差功能是使用的阿里云NTP时间校正，请问能不能增加通过HTTP响应头的Date以cpp服务器为时钟源进行时间校正功能呢？
![响应头截图](https://github.com/user-attachments/assets/9372a244-b061-4e5d-9653-60ab9a4460db)

**Comment by mikumifa** [comment]
理论不可以，参考https://info.support.huawei.com/info-finder/encyclopedia/zh/NTP.html
