### ISSUE TITLE
[Bug]: 已购票时开抢不会停止请求

### ISSUE THREAD

**Issue by Allroha** [mikumifa/cppTickerBuy#9]
### 部署方式

release的打包文件

### 版本

0.02

### 异常情况

![2024-09-16_20-10-07](https://github.com/user-attachments/assets/1f5000ec-f8e6-4bbe-8e9f-6c7bf5490565)

在抢到票后不会停止请求
可以考虑添加一下对内容的状态检测

**Comment by mikumifa** [comment]
会改到
